### ISSUE TITLE
OutOfMemoryException

### ISSUE THREAD

**Issue by ThomasArdal** [NoelKennedy/MinimumEditDistance#1]
The following code throws a OutOfMemoryException:

``` csharp
using System;
using System.Net;
using MinimumEditDistance;

namespace LevenshteinTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var webClient = new WebClient();
            var html1 = webClient.DownloadString("http://www.google.com");
            var html2 = webClient.DownloadString("http://www.google.com");
            var distance = Levenshtein.CalculateDistance(html1, html2, 1);
            Console.WriteLine("Distance: " + distance);
            Console.ReadLine();
        }
    }
}
```

The exceptions is thrown in the CalculateDistance method.

**Comment by NoelKennedy** [comment]
Thanks for reporting, will take a look.

**Comment by NoelKennedy** [comment]
ok, those strings are quite long: 43,586 characters.  Levenshtein uses dynamic programming and so would need  to allocate a 7gb array to calculate the difference (43586^2) \* 4 bytes per Int.  I think there is a 2GB limit on single objects in the CLR.  Potentially it could be done using a jagged array but is it possible to reduce the problem by partitioning the comparison you need to do?.

**Comment by ThomasArdal** [comment]
I've implemented some code that works on top of your code. I'm splitting the string into an array of strings and validate them one at the time. But the distance is larger than it would if calculating on the entire string.

Example:

string 1: Loremipsumdolorsitamet
string 2: consecteturadipisicingelit
Distance = 19

When split into strings:

strings 1: Lorem, ipsum, dolor, sitam, et
strings 2: conse, ctetu, radip, isici, ngeli, t
Distance = 4, 5, 5, 4, 4, 1 = 23

**Comment by NoelKennedy** [comment]
Hm, I think it would be best to go with jagged arrays then to get around the 2 GB limit.  Will alter it and let you know when it's done.

**Comment by ThomasArdal** [comment]
Sounds great! :)

**Comment by NoelKennedy** [comment]
I've developed a new version that can handle extremely long string comparisons.  It is now bounded above by the maximum addressable memory for the CLR process which I think is about 8 terrabytes for 64 bit!

It's published to nuget if you use that.

**Comment by ThomasArdal** [comment]
Great. I'm using NuGet and will test the new version later tonight. Thank you so much, Noel.

**Comment by ThomasArdal** [comment]
I'm still experiencing the OutOfMemoryException on the new version of the NuGet package. Is there a maximum on the input strings? The Google download is around 43k characters.

**Comment by NoelKennedy** [comment]
Try using the other over load and passing in a JaggedArray instance. What
number do you get when you multiply the lengths of the two strings? Are you
running 32 bit or 64?

Cheers!

**Comment by NoelKennedy** [comment]
There isn't a Max length on strings per se, the problem is the allocation
of the memory space to solve the problem. You can test that yourself by
instantiating an array new int[length str1,length string2]. If you create
an instance of red class in my package called JaggedArray with constructor
params str1.Length, str2.length it should work I hope!

**Comment by ThomasArdal** [comment]
Sorry didn't spot the overload. I'll try that tonight and get back to you.

**Comment by ThomasArdal** [comment]
x64 using the new JaggedArray works like a charm. Thank you so much for your help.

**Comment by NoelKennedy** [comment]
No probs!
